ALTER TABLE `objects` CHANGE `NumRooms` `RoomsTotal` INT(11) NOT NULL;
ALTER TABLE `objects` ADD `RoomsIsolated` INT NOT NULL AFTER `RoomsTotal`;
ALTER TABLE `objects` ADD `SpaceTotal` DECIMAL(7,1) NOT NULL AFTER `RoomsIsolated`, ADD `SpaceLiving` DECIMAL(7,1) NOT NULL AFTER `SpaceTotal`, ADD `SpaceKitchen` DECIMAL(7,1) NOT NULL AFTER `SpaceLiving`;
ALTER TABLE `objects` ADD `Layers` TINYINT NOT NULL DEFAULT '1' AFTER `Floors`, ADD `Toilets` TINYINT NOT NULL DEFAULT '1' AFTER `Layers`, ADD `Balconies` TINYINT NOT NULL DEFAULT '0' AFTER `Toilets`, ADD `Loggias` TINYINT NOT NULL DEFAULT '0' AFTER `Balconies`, ADD `CeilingHeight` DECIMAL(4,1) NOT NULL AFTER `Loggias`, ADD `CostPerMeter` DECIMAL(12,1) NOT NULL AFTER `CeilingHeight`, ADD `Entrance` VARCHAR(64) NOT NULL AFTER `CostPerMeter`;
ALTER TABLE `objects` CHANGE `Entrance` `Entrances` INT NOT NULL DEFAULT '1';
ALTER TABLE `objects` ADD `Elevators` INT NOT NULL AFTER `Entrances`;
ALTER TABLE `objects` ADD `OverlappingTypeID` INT(5) NOT NULL  AFTER `Problem`,  ADD `CompletionDateQuarter` INT NOT NULL  AFTER `OverlappingTypeID`,  ADD `CompletionDateYear` INT NOT NULL  AFTER `CompletionDateQuarter`,  ADD `LayoutTypeID` INT NOT NULL DEFAULT '1'  AFTER `CompletionDateYear`,  ADD `ToiletTypeID` INT NOT NULL DEFAULT '1'  AFTER `LayoutTypeID`,  ADD `ConditionID` INT NOT NULL DEFAULT '1'  AFTER `ToiletTypeID`,  ADD `FinishingID` INT NOT NULL DEFAULT '1'  AFTER `ConditionID`,  ADD `FloorSurfaceID` INT NOT NULL DEFAULT '1'  AFTER `FinishingID`,  ADD `StoveTypeID` INT NOT NULL DEFAULT '1'  AFTER `FloorSurfaceID`,  ADD `DoorsTypeID` INT NOT NULL DEFAULT '1'  AFTER `StoveTypeID`,  ADD `WallsSurfaceID` INT NOT NULL DEFAULT '1'  AFTER `DoorsTypeID`,  ADD `WallsMaterialID` INT NOT NULL DEFAULT '1'  AFTER `WallsSurfaceID`,  ADD `BathroomEquipmentID` INT NOT NULL DEFAULT '1'  AFTER `WallsMaterialID`,  ADD `WindowsTypeID` INT NOT NULL DEFAULT '1'  AFTER `BathroomEquipmentID`,  ADD `RightsSourceID` INT NOT NULL DEFAULT '1'  AFTER `WindowsTypeID`,  ADD `RightsTransmissionID` INT NOT NULL DEFAULT '1'  AFTER `RightsSourceID`,  ADD `ResidentialComplexName` VARCHAR(256) NOT NULL  AFTER `RightsTransmissionID`,  ADD `Developer` VARCHAR(128) NOT NULL  AFTER `ResidentialComplexName`;
ALTER TABLE `objects` ADD `Security` TINYINT NOT NULL DEFAULT '1' AFTER `OverlappingTypeID`, ADD `Concierge` TINYINT NOT NULL DEFAULT '1' AFTER `Security`, ADD `OperationService` TINYINT NOT NULL DEFAULT '1' AFTER `Concierge`, ADD `Chute` TINYINT NOT NULL DEFAULT '1' AFTER `OperationService`, ADD `Gas` TINYINT NOT NULL DEFAULT '1' AFTER `Chute`, ADD `Parking` TINYINT NOT NULL DEFAULT '1' AFTER `Gas`;

